version: "3"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: devise-inspection
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: devise-inspection
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - .:/devise-inspection
    links:
      - mysql
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    tty: true
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
